[project]
name = "scrapyon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.39.0",
    "httpx==0.27.2",
    "pydantic>=2.10.3",
    "scrapybara>=2.0.0",
]
